include("sll_show_tests.jl")
include("sll_parser_tests.jl")
include("algebra_tests.jl")
include("he_tests.jl")
include("msg_tests.jl")
include("process_tree_tests.jl")
# include("basic_process_tree_builder_tests.jl")
